# numpy Assignment

1: Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde. 

In [1]:
import numpy as np

def atv(x, N, increasing = False):  #Alexandre- Theophile Vandermonde. 
    if increasing:
        return np.column_stack([x**i for i in range(N)])
    else:
        return np.column_stack([x**(N-i-1) for i in range(N)])        

In [2]:
x =  np.array([1,2,7,3,4])
y_increasing = atv(x,7,True)
print(y_increasing)

[[     1      1      1      1      1      1      1]
 [     1      2      4      8     16     32     64]
 [     1      7     49    343   2401  16807 117649]
 [     1      3      9     27     81    243    729]
 [     1      4     16     64    256   1024   4096]]


In [3]:
y_notincreasing = atv(x,7,False)
print(y_notincreasing)

[[     1      1      1      1      1      1      1]
 [    64     32     16      8      4      2      1]
 [117649  16807   2401    343     49      7      1]
 [   729    243     81     27      9      3      1]
 [  4096   1024    256     64     16      4      1]]


2: Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence.

In [4]:
import numpy as np
def movingavg(x,N):
    x=np.array(x)
    return np.array([np.mean(x[i:i+N]) for i in range(len(x)-N+1)])

In [5]:
print(list(range(10,110,10)))
movingavg(range(10,110,10),4)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


array([25., 35., 45., 55., 65., 75., 85.])

In [6]:
np.set_printoptions(precision=2)
movingavg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])